from __future__ import annotations

import json
import os
import subprocess
import asyncio
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional
from mutagen.mp3 import MP3
from jinja2 import Template

from app.config import settings
from app.models import DirectVideoRequest

class RemotionService:
    def __init__(self) -> None:
        self.remotion_path = Path("Remotion")
        self.output_dir = settings.output_dir / "template_output"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.audio_dir = self.remotion_path / "public" / "audio"
        self.audio_dir.mkdir(parents=True, exist_ok=True)
        self.metadata_path = self.remotion_path / "public" / "metadata.json"

    def _time_to_sec(self, t_str: str) -> float:
        """Converts 00:00:00,000 to seconds float."""
        try:
            h, m, s = t_str.split(':')
            s, ms = s.split(',')
            return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0
        except:
            return 0.0

    def _parse_vtt(self, vtt_path: Path) -> List[Dict[str, Any]]:
        """Parses a basic WebVTT file generated by edge-tts CLI."""
        subtitles = []
        if not vtt_path.exists():
            return []
            
        content = vtt_path.read_text(encoding='utf-8')
        # Use regex to find subtitle blocks
        pattern = re.compile(r"\d+\n(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})\n(.+?)(?=\n\n|\Z)", re.DOTALL)
        
        matches = pattern.findall(content)
        for start_str, end_str, text in matches:
            subtitles.append({
                "text": text.replace('\n', ' ').strip(),
                "start": self._time_to_sec(start_str),
                "end": self._time_to_sec(end_str)
            })
        return subtitles

    def _update_metadata(self, job_id: str, duration: float, subtitles: List[Dict[str, Any]]) -> None:
        """Updates the global metadata.json with job details."""
        metadata = {}
        if self.metadata_path.exists():
            try:
                metadata = json.loads(self.metadata_path.read_text(encoding='utf-8'))
            except:
                pass
        
        metadata[job_id] = {
            "duration": duration,
            "subtitles": subtitles,
            "tts_provider": "edge"
        }
        
        self.metadata_path.write_text(json.dumps(metadata, indent=4, ensure_ascii=False), encoding='utf-8')

    async def generate_tts(self, request: DirectVideoRequest) -> Dict[str, Any]:
        """
        Generates TTS using edge-tts.
        """
        VOICE_MAP = {
            "English": "en-US-EmmaMultilingualNeural",
            "Hindi": "hi-IN-SwaraNeural",
            "Tamil": "ta-IN-PallaviNeural",
            "Telugu": "te-IN-MohanNeural",
            "Marathi": "mr-IN-AarohiNeural",
            "Kannada": "kn-IN-SapnaNeural",
            "Bengali": "bn-IN-TanishaNeural",
            "Gujarati": "gu-IN-DhwaniNeural",
            "Malayalam": "ml-IN-SobhanaNeural",
            "Punjabi": "pa-IN-KritikaNeural"
        }

        language = request.language or "Hindi"
        voice = VOICE_MAP.get(language, "hi-IN-SwaraNeural")

        if request.script_text:
            text_template = request.script_text
        else:
            # Default scripts per language (using Jinja2 syntax consistently)
            SCRIPTS = {
                "Hindi": """नमस्ते {{ customer_name }}।
मैं {{ client_name }} के कानूनी विभाग से बात कर रही हूँ। यह आपके {{ product_type }} के संबंध में एक अत्यंत महत्वपूर्ण और औपचारिक सूचना है।
आपके ऋण खाते, जिसकी कुल राशि {{ loan_amount }} है, में पिछले कई महीनों से भुगतान नहीं किया गया है।
वर्तमान में आपकी कुल बकाया राशि {{ tos }} हो चुकी है। बार-बार याद दिलाने के बावजूद, आपकी ओर से कोई सकारात्मक प्रतिक्रिया नहीं मिली है।
इसी कारणवश, बैंक ने अब आपके विरुद्ध 'लोन रिकॉल नोटिस' (Loan Recall Notice) जारी करने का कड़ा निर्णय लिया है।
इसका अर्थ यह है कि अब आपको पूरी ऋण राशि का भुगतान तुरंत एक साथ करना होगा।
यदि आप अगले 48 घंटों के भीतर हमसे संपर्क नहीं करते हैं, तो हमारे पास कानूनी आर्बिट्रेशन (Arbitration) की प्रक्रिया शुरू करने के अलावा कोई विकल्प नहीं बचेगा। 
इस प्रक्रिया में आपकी संपत्ति की कुर्की और नीलामी भी शामिल हो सकती है, जिसका सारा खर्च और कानूनी शुल्क आपको ही वहन करना होगा।
कृपया इस चेतावनी को गंभीरता से लें। हम अभी भी आपसी समझौते के माध्यम से इस मामले को हल करने के इच्छुक हैं। 
भविष्य की कानूनी पेचीदगियों और अपनी क्रेडिट रेटिंग को बचाने के लिए कृपया तुरंत {{ contact_details }} पर कॉल करें।
धन्यवाद।""",
                "English": """Hello {{ customer_name }}. 
I am calling from the legal department of {{ client_name }}. This is an extremely important and formal notice regarding your {{ product_type }}.
Your loan account, with a total amount of {{ loan_amount }}, has not been paid for several months.
Currently, your total outstanding balance is {{ tos }}. Despite repeated reminders, there has been no positive response from your side.
For this reason, the bank has now taken a tough decision to issue a 'Loan Recall Notice' against you.
This means that you now have to pay the entire loan amount immediately at once.
If you do not contact us within the next 48 hours, we will have no choice but to initiate the process of legal arbitration.
This process may also include the attachment and auction of your property, the entire cost and legal fees of which will have to be borne by you.
Please take this warning seriously. We are still interested in resolving this matter through a mutual settlement.
To save future legal complications and your credit rating, please call immediately at {{ contact_details }}.
Thank you.""",
                "Marathi": """नमस्कार {{ customer_name }}.
मी {{ client_name }} च्या कायदेशीर विभागातून बोलत आहे. ही तुमच्या {{ product_type }} संदर्भात अत्यंत महत्त्वाची आणि औपचारिक सूचना आहे.
तुमचे कर्ज खाते, ज्याची एकूण रक्कम {{ loan_amount }} आहे, गेल्या अनेक महिन्यांपासून भरलेले नाही.
सध्या तुमची एकूण थकबाकी {{ tos }} झाली आहे. वारंवार आठवण करून देऊनही तुमच्याकडून कोणताही सकारात्मक प्रतिसाद मिळालेला नाही.
या कारणास्तव, बँकेने आता तुमच्या विरोधात 'लोन रिकॉल नोटीस' (Loan Recall Notice) जारी करण्याचा कठोर निर्णय घेतला आहे.
याचा अर्थ असा की आता तुम्हाला संपूर्ण कर्जाची रक्कम त्वरित एकाच वेळी भरावी लागेल.
जर तुम्ही पुढील ४८ तासांच्या आत आमच्याशी संपर्क साधला नाही, तर आमच्याकडे कायदेशीर लवाद (Arbitration) प्रक्रिया सुरू करण्याशिवाय कोणताही पर्याय उरणार नाही.
या प्रक्रियेत तुमच्या मालमत्तेची जપ્ती आणि लिलाव देखील समाविष्ट असू शकतो, ज्याचा सर्व खर्च आणि कायदेशीर शुल्क तुम्हालाच सहन करावे लागेल.
कृपया ही चेतावणी गांभीर्याने घ्या. आम्ही अजूनही परस्पर तडजोडीद्वारे हे प्रकरण सोडवण्यास उत्सुक आहोत.
भविष्यातील कायदेशीर गुंतागुंत आणि तुमचे क्रेडिट रेटिंग वाचवण्यासाठी कृपया त्वरित {{ contact_details }} वर कॉल करा.
धन्यवाद.""",
                "Tamil": """வணக்கம் {{ customer_name }}.
நான் {{ client_name }} சட்டத் துறையிலிருந்து பேசுகிறேன். இது உங்கள் {{ product_type }} தொடர்பான மிகவும் முக்கியமான மற்றும் முறையான அறிவிப்பாகும்.
உங்களின் {{ loan_amount }} மொத்தத் தொகையிலான கடன் கணக்கு கடந்த பல மாதங்களாகச் செலுத்தப்படவில்லை.
தற்போது உங்களின் மொத்த நிலுவைத் தொகை {{ tos }} ஆக உள்ளது. பலமுறை நினைவூட்டியும், உங்கள் தரப்பிலிருந்து எந்தவித நேர்மறையான பதிலும் இல்லை.
இந்தக் காரணத்திற்காக, வங்கி இப்போது உங்களுக்கு எதிராக 'லோன் ரீகால் நோட்டீஸ்' (Loan Recall Notice) அனுப்பக் கடுமையான முடிவை எடுத்துள்ளது.
இதன் பொருள் நீங்கள் இப்போது முழு கடன் தொகையையும் உடனடியாக ஒரே நேரத்தில் செலுத்த வேண்டும் என்பதாகும்.
அடுத்த 48 மணிநேரத்திற்குள் நீங்கள் எங்களைத் தொடர்பு கொள்ளவில்லை என்றால், சட்டப்பூர்வ நடுவர் (Arbitration) நடவடிக்கையைத் தொடங்குவதைத் தவிர எங்களுக்கு வேறு வழி இருக்காது.
இந்தச் செயல்முறை உங்கள் சொத்துக்களைப் பறிமுதல் செய்வது மற்றும் ஏலம் விடுவதையும் உள்ளடக்கியிருக்கலாம், இதற்கான முழுச் செலவு மற்றும் சட்டக் கட்டணங்களை நீங்களே ஏற்க வேண்டியிருக்கும்.
தயவுசெய்து இந்த எச்சரிக்கையைத் தீவிரமாக எடுத்துக் கொள்ளுங்கள். பரஸ்பர தீர்வு மூலம் இந்த விவகாரத்தைத் தீர்க்க நாங்கள் இன்னும் ஆர்வமாக உள்ளோம்.
எதிர்காலச் சட்டச் சிக்கல்கள் மற்றும் உங்கள் கிரெடிட் ரேட்டிங்கைப் பாதுகாக்க, தயவுசெய்து உடனடியாக {{ contact_details }} என்ற எண்ணைத் தொடர்பு கொள்ளவும்.
நன்றி.""",
                "Telugu": """నమస్కారం {{ customer_name }}.
నేను {{ client_name }} చట్టపరమైన విభాగం నుండి మాట్లాడుతున్నాను. ఇది మీ {{ product_type }} సంబంధించి అత్యంత ముఖ్యమైన మరియు అధికారిక నోటీసు.
మీ రుణ ఖాతా, దీని మొత్తం {{ loan_amount }}, గత కొన్ని నెలలుగా చెల్లించబడలేదు.
ప్రస్తుతం మీ మొత్తం బకాయి {{ tos }} కి చేరుకుంది. పదేపదే రిమైండర్‌లు పంపినప్పటికీ, మీ వైపు నుండి ఎటువంటి సానుకూల స్పందన లేదు.
ఈ కారణంగా, బ్యాంక్ ఇప్పుడు మీపై 'లోన్ రీకాల్ నోటీసు' (Loan Recall Notice) జారీ చేయాలని కఠిన నిర్ణయం తీసుకుంది.
దీని అర్థం మీరు ఇప్పుడు మొత్తం రుణ మొత్తాన్ని వెంటనే ఒకేసారి చెల్లించాలి.
తదుపరి 48 గంటల్లోగా మీరు మమ్మల్ని సంప్రదించకపోతే, చట్టపరమైన మధ్యవర్తిత్వం (Arbitration) ప్రక్రియను ప్రారంభించడం మినహా మాకు వేరే మార్గం ఉండదు.
ఈ ప్రక్రియలో మీ ఆస్తిని జప్తు చేయడం మరియు వేలం వేయడం కూడా ఉండవచ్చు, దీని మొత్తం ఖర్చు మరియు చట్టపరమైన రుసుములను మీరే భరించాల్సి ఉంటుంది.
దయచేసి ఈ హెచ్చరికను తీవ్రంగా పరిగణించండి. పరస్పర పరిష్కారం ద్వారా ఈ విషయాన్ని పరిష్కరించుకోవడానికి మేము ఇంకా సుముఖంగా ఉన్నాము.
భవిష్యత్తులో చట్టపరమైన చిక్కులు మరియు మీ క్రెడిట్ రేటింగ్‌ను కాపాడుకోవడానికి దయచేసి వెంటనే {{ contact_details }} నంబర్‌కు కాల్ చేయండి.
ధన్యవాదాలు.""",
                "Kannada": """ನಮಸ್ಕಾರ {{ customer_name }}.
ನಾನು {{ client_name }} ಕಾನೂನು ವಿಭಾಗದಿಂದ ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ. ಇದು ನಿಮ್ಮ {{ product_type }} ಗೆ ಸಂಬಂಧಿಸಿದ ಅತ್ಯಂತ ಪ್ರಮುಖ ಮತ್ತು ಅಧಿಕೃತ ಸೂಚನೆಯಾಗಿದೆ.
ನಿಮ್ಮ ಸಾಲದ ಖಾತೆ, ಇದರ ಒಟ್ಟು ಮೊತ್ತ {{ loan_amount }}, ಕಳೆದ ಹಲವಾರು ತಿಂಗಳುಗಳಿಂದ ಪಾವತಿಸಲ್ಪಟ್ಟಿಲ್ಲ.
ಪ್ರಸ್ತುತ ನಿಮ್ಮ ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ {{ tos }} ಆಗಿರುತ್ತದೆ. ಪದೇ ಪದೇ ನೆನಪಿಸಿದರೂ ನಿಮ್ಮ ಕಡೆಯಿಂದ ಯಾವುದೇ ಸಕಾರಾತ್ಮಕ ಪ್ರತಿಕ್ರಿಯೆ ಬಂದಿಲ್ಲ.
ಈ ಕಾರಣಕ್ಕಾಗಿ, ಬ್ಯಾಂಕ್ ಈಗ ನಿಮ್ಮ ವಿರುದ್ಧ 'ಸಾಲ ಹಿಂಪಡೆಯುವ ಸೂಚನೆ' (Loan Recall Notice) ಹೊರಡಿಸುವ ಕಠಿಣ ನಿರ್ಧಾರವನ್ನು ತೆಗೆದುಕೊಂಡಿದೆ.
ಇದರರ್ಥ ನೀವು ಈಗ ಸಂಪೂರ್ಣ ಸಾಲದ ಮೊತ್ತವನ್ನು ಕೂಡಲೇ ಒಂದು ಹಂತದಲ್ಲಿ ಪಾವತಿಸಬೇಕಾಗುತ್ತದೆ.
ಮುಂದಿನ 48 ಗಂಟೆಗಳ ಒಳಗೆ ನೀವು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸದಿದ್ದರೆ, ಕಾನೂನು ಮಧ್ಯಸ್ಥಿಕೆ (Arbitration) ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸುವುದರ ಹೊರತಾಗಿ ನಮಗೆ ಬೇರೆ ಆಯ್ಕೆ ಇರುವುದಿಲ್ಲ.
ಈ ಪ್ರಕ್ರಿಯೆಯು ನಿಮ್ಮ ಆಸ್ತಿಯ ಮುಟ್ಟುಗೋಲು ಮತ್ತು ಹರಾಜನ್ನು ಸಹ ಒಳಗೊಂಡಿರಬಹುದು, ಇದರ ಸಂಪೂರ್ಣ ವೆಚ್ಚ ಮತ್ತು ಕಾನೂನು ಶುಲ್ಕಗಳನ್ನು ನೀವೇ ಭರಿಸಬೇಕಾಗುತ್ತದೆ.
ದಯವಿಟ್ಟು ಈ ಎಚ್ಚರಿಕೆಯನ್ನು ಗಂಭೀರವಾಗಿ ಪರಿಗಣಿಸಿ. ಪರಸ್ಪರ ಪતાવಟೆಯ ಮೂಲಕ ಈ ವಿಷಯವನ್ನು ಬಗೆಹರಿಸಲು ನಾವು ಇಂದಿಗೂ ಇಚ್ಛಿಸುತ್ತೇವೆ.
ಭವಿಷ್ಯದ ಕಾನೂನು ತೊಡಕುಗಳು ಮತ್ತು ನಿಮ್ಮ ಕ್ರೆಡಿಟ್ ರೇಟಿಂಗ್ ಅನ್ನು ಉಳಿಸಿಕೊಳ್ಳಲು ದಯವಿಟ್ಟು ಕೂಡಲೇ {{ contact_details }} ಸಂಖ್ಯೆಗೆ ಕರೆ ಮಾಡಿ.
ಧನ್ಯವಾದಗಳು.""",
                "Bengali": """নমস্কার {{ customer_name }}।
আমি {{ client_name }} আইনি বিভাগ থেকে কথা বলছি। এটি আপনার {{ product_type }} সংক্রান্ত একটি অত্যন্ত গুরুত্বপূর্ণ এবং আনুষ্ঠানিক বিজ্ঞপ্তি।
আপনার ঋণ অ্যাকাউন্ট, যার মোট পরিমাণ {{ loan_amount }}, গত কয়েকমাস ধরে পরিশোধ করা হয়নি।
বর্তমানে আপনার মোট বকেয়া পরিমাণ {{ tos }} হয়েছে। বারবার মনে করিয়ে দেওয়া সত্ত্বেও আপনার পক্ষ থেকে কোনো ইতিবাচক প্রতিক্রিয়া পাওয়া যায়নি।
এই কারণে, ব্যাংক এখন আপনার বিরুদ্ধে 'লোন রিকল নোটিশ' (Loan Recall Notice) জারি করার কঠোর সিদ্ধান্ত নিয়েছে।
এর অর্থ হলো আপনাকে এখন পুরো ঋণের টাকা অবিলম্বে একসাথে পরিশোধ করতে হবে।
আগামী ৪৮ ঘণ্টার মধ্যে আপনি আমাদের সাথে যোগাযোগ না করলে, আইনি সালিশি (Arbitration) প্রক্রিয়া শুরু করা ছাড়া আমাদের কাছে আর কোনো উপায় থাকবে না।
এই প্রক্রিয়ায় আপনার সম্পত্তি বাজেয়াপ্ত ও নিলামও করা হতে পারে, যার সমস্ত খরচ এবং আইনি ফি আপনাকেই বহন করতে হবে।
অনুগ্রহ করে এই সতর্কতাটি গুরুত্ব সহকারে নিন। আমরা এখনও পারস্পরিক নিষ্পত্তির মাধ্যমে এই বিষয়টি সমাধান করতে আগ্রহী।
ভবিষ্যতের আইনি জটিলতা এবং আপনার ক্রেডিট রেটিং বাঁচাতে অনুগ্রহ করে অবিলম্বে {{ contact_details }} নম্বরে কল করুন।
ধন্যবাদ।""",
                "Gujarati": """નમસ્તે {{ customer_name }}.
હું {{ client_name }} ના કાનૂની વિભાગમાંથી બોલી રહ્યો છું. આ તમારા {{ product_type }} સંદર્ભમાં અત્યંત મહત્વપૂર્ણ અને ઔપચારિક સૂચના છે.
તમારું લોન ખાતું, જેની કુલ રકમ {{ loan_amount }} છે, છેલ્લા ઘણા મહિનાઓથી ભરવામાં આવ્યું નથી.
હાલમાં તમારી કુલ બાકી રકમ {{ tos }} થઈ ગઈ છે. વારંવાર યાદ અપાવવા છતાં તમારા તરફથી કોઈ સકારાત્મક પ્રતિસાદ મળ્યો નથી.
આ કારણોસર, બેંકે હવે તમારી વિરુદ્ધ 'લોન રિકોલ નોટિસ' (Loan Recall Notice) જારી કરવાનો કડક નિર્ણય લીધો છે.
આનો અર્થ એ છે કે હવે તમારે આખી લોનની રકમ તરત જ એકસાથે ચૂકવવી પડશે.
જો તમે આગામી 48 કલાકમાં અમારો સંપર્ક નહીં કરો, તો અમારી પાસે કાનૂની આર્બિટ્રેશન (Arbitration) પ્રક્રિયા શરૂ કરવા સિવાય કોઈ વિકલ્પ રહેશે નહીં.
આ પ્રક્રિયામાં તમારી મિલકતની જપ્તી અને હરાજી પણ સામેલ હોઈ શકે છે, જેનો તમામ खर्च અને કાનૂની ફી તમારે જ ભોગવવી પડશે.
કૃપા કરીને આ ચેતવણીને ગંભીરતાથી લો. અમે હજી પણ પરસ્પર સમાધાન દ્વારા આ બાબતને ઉકેલવા ઈચ્છીએ છીએ.
ભવિષ્યની કાનૂની ગૂંચવણો અને તમારા ક્રેડિટ રેટિંગને બચાવવા માટે કૃપા કરીને તરત જ {{ contact_details }} પર કોલ કરો.
આભાર.""",
                "Malayalam": """നമസ്കാരം {{ customer_name }}.
ഞാൻ {{ client_name }} നിയമ വിഭാഗത്തിൽ നിന്നാണ് സംസാരിക്കുന്നത്. നിങ്ങളുടെ {{ product_type }} സംബന്ധിച്ച അതീവ പ്രാധാന്യമുള്ളതും ഔദ്യോഗികവുമായ ஒரு അറിയിപ്പാണിത്.
നിങ്ങളുടെ {{ loan_amount }} ആകെ തുകയുള്ള വായ്പാ അക്കൗണ്ടിൽ കഴിഞ്ഞ കുറച്ചു മാസങ്ങളായി തിരിച്ചടവ് നടത്തിയിട്ടില്ല.
നിലവിൽ നിങ്ങളുടെ ആകെ കുടിശ്ശിക {{ tos }} ആയി മാറിയിരിക്കുന്നു. പലതവണ ഓർമ്മിപ്പിച്ചിട്ടും നിങ്ങളുടെ ഭാഗത്തുനിന്ന് അനുകൂലമായ പ്രതികരണമൊന്നും ഉണ്ടായിട്ടില്ല.
ഈ കാരണത്താൽ, ബാങ്ക് ഇപ്പോൾ നിങ്ങൾക്കെതിരെ 'ലോൺ റീകോൾ നോട്ടീസ്' (Loan Recall Notice) പുറപ്പെടുവിക്കാൻ കടുത്ത തീരുമാനമെടുത്തിരിക്കുകയാണ്.
ഇതിനർത്ഥം നിങ്ങൾ ഇപ്പോൾ മുഴുവൻ വായ്പാ തുകയും ഉടൻ തന്നെ ഒന്നിച്ച് അടയ്ക്കണം എന്നാണ്.
അടുത്ത 48 മണിക്കൂറിനുള്ളിൽ നിങ്ങൾ ഞങ്ങളെ ബന്ധപ്പെടുന്നില്ലെങ്കിൽ നിയമപരമായ ആർബിട്രേഷൻ (Arbitration) നടപടികൾ ആരംഭിക്കുകയല്ലാതെ ഞങ്ങൾക്ക് മറ്റ് മാർഗമില്ല.
ഈ പ്രക്രിയയിൽ നിങ്ങളുടെ സ്വത്ത് കണ്ടുകെട്ടുന്നതും ലേലം ചെയ്യുന്നതും ഉൾപ്പെടാം, ഇതിന്റെ മുഴുവൻ ചിലവും നിയമപരമായ ഫീസും നിങ്ങൾ തന്നെ വഹിക്കേണ്ടി വരും.
ദയവായി ഈ മുന്നറിയിപ്പ് ഗൗരവമായി കാണുക. ഉഭയകക്ഷി ഒത്തുതീർപ്പിലൂടെ ഈ വിഷയം പരിഹരിക്കാൻ ഞങ്ങൾ ഇപ്പോഴും താല്പര്യപ്പെടുന്നു.
ഭാവിയിലെ നിയമപ്രശ്നങ്ങളും നിങ്ങളുടെ ക്രെഡിറ്റ് റേറ്റിംഗും സംരക്ഷിക്കുന്നതിനായി ദയവായി ഉടൻ തന്നെ {{ contact_details }} എന്ന നമ്പറിൽ വിളിക്കുക.
നന്ദി.""",
                "Punjabi": """ਨਮਸਤੇ {{ customer_name }}।
ਮੈਂ {{ client_name }} ਦੇ ਕਾਨੂੰਨੀ ਵਿਭਾਗ ਤੋਂ ਗੱਲ ਕਰ ਰਿਹਾ ਹਾਂ। ਇਹ ਤੁਹਾਡੇ {{ product_type }} ਦੇ ਸਬੰਧ ਵਿੱਚ ਇੱਕ ਬਹੁਤ ਮਹੱਤਵਪੂਰਨ ਅਤੇ ਰਸਮੀ ਨੋਟਿਸ ਹੈ।
ਤੁਹਾਡਾ ਕਰਜ਼ਾ ਖਾਤਾ, ਜਿਸਦੀ ਕੁੱਲ ਰਕਮ {{ loan_amount }} ਹੈ, ਪਿਛਲੇ ਕਈ ਮਹੀਨਿਆਂ ਤੋਂ ਭਰਿਆ ਨਹੀਂ ਗਿਆ ਹੈ।
ਵਰਤਮਾਨ ਵਿੱਚ ਤੁਹਾਡੀ ਕੁੱਲ ਬਕਾਇਆ ਰਕਮ {{ tos }} ਹੋ ਗਈ ਹੈ। ਵਾਰ-ਵਾਰ ਯਾਦ ਦਿਵਾਉਣ ਦੇ ਬਾਵਜੂਦ ਤੁਹਾਡੇ ਵੱਲੋਂ ਕੋਈ ਸਾਕਾਰਾਤਮਕ ਹੁੰਗਾਰਾ ਨਹੀਂ ਮਿਲਿਆ।
ਇਸ ਕਾਰਨ ਬੈਂਕ ਨੇ ਹੁਣ ਤੁਹਾਡੇ ਵਿਰੁੱਧ 'ਲੋਨ ਰੀਕਾਲ ਨੋਟਿਸ' (Loan Recall Notice) ਜਾਰੀ ਕਰਨ ਦਾ ਸਖ਼ਤ ਫੈਸਲਾ ਲਿਆ ਹੈ।
ਇਸਦਾ ਮਤલਬ ਹੈ ਕਿ ਹੁਣ ਤੁਹਾਨੂੰ ਪੂਰੀ ਕਰਜ਼ਾ ਰਕਮ ਤੁਰੰਤ ਇੱਕੋ ਵਾਰ ਅਦਾ ਕਰਨੀ ਪਵੇਗੀ।
ਜੇਕਰ ਤੁਸੀਂ ਅਗਲੇ 48 ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਸਾਧੇ ਨਾਲ ਸੰਪਰਕ ਨਹੀਂ ਕਰਦੇ ਹੋ, ਤਾਂ ਸਾਡੇ ਕੋਲ ਕਾਨੂੰਨੀ ਆਰਬਿਟਰేਸ਼ਨ (Arbitration) ਦੀ ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰೂ ਕਰਨ ਤੋਂ ਇਲਾਵਾ ਕੋਈ ਹੋਰ ਚਾਰਾ ਨਹੀਂ ਬਚੇਗਾ।
ਇਸ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਦੀ ਕੁਰਕੀ ਅਤੇ ਨਿਲਾਮੀ ਵੀ ਸ਼ਾਮਲ ਹੋ ਸਕਦੀ ਹੈ, ਜਿਸਦਾ ਸਾਰਾ ਖਰਚਾ ਅਤੇ ਕਾਨੂੰਨੀ ਫੀਸ ਤੁਹਾਨੂੰ ਹੀ ਭਰਨੀ ਪਵੇਗੀ।
ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਚੇਤਾਵਨੀ ਨੂੰ ਗੰਭીરਤਾ ਨਾਲ ਲਓ। ਅਸੀਂ ਅਜੇ ਵੀ ਆਪਸੀ ਸਮਝੌਤੇ ਰਾਹੀਂ ਇਸ ਮਾਮле ਨੂੰ ਹੱਲ ਕਰਨ ਦੇ ਇੱਛੁਕ ਹਾਂ।
ਭਵਿੱਖ ਦੀਆਂ ਕਾਨੂੰਨੀ ਪੇਚੀਦਗੀਆਂ ਅਤੇ ਆਪਣੀ ਕ੍ਰੈਡਿಟ್ ਰੇਟਿੰਗ ਨੂੰ ਬਚਾਉਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਤੁਰੰਤ {{ contact_details }} 'ਤੇ ਕਾਲ ਕਰੋ।
ਧੰਨਵਾਦ।"""
            }
            text_template = SCRIPTS.get(language, SCRIPTS["English"])
            
        # Support single bracket {placeholder} by converting to {{placeholder}}
        # This makes it easier for manual user entry
        processed_template = re.sub(r'(?<!{){([^{}\s]+)}(?!})', r'{{\1}}', text_template)
            
        # Render the template with lead data
        template = Template(processed_template)
        
        # Prepare context with shorthands for common variables
        render_context = {
            "customer_name": request.customer_name or "Customer",
            "customer": request.customer_name or "Customer",
            "client_name": request.client_name or "Bank",
            "client": request.client_name or "Bank",
            "loan_amount": request.loan_amount or "amount",
            "loan_amt": request.loan_amount or "amount",
            "amt": request.loan_amount or "amount",
            "tos": request.tos or "outstanding",
            "balance": request.tos or "outstanding",
            "outstanding": request.tos or "outstanding",
            "lan": request.lan or "N/A",
            "account_number": request.lan or "N/A",
            "contact_details": request.contact_details or "1800-XXX-XXXX",
            "helpline": request.contact_details or "1800-XXX-XXXX",
            "contact": request.contact_details or "1800-XXX-XXXX",
            "product_type": request.product_type or "loan",
            "product": request.product_type or "loan"
        }
        
        text_content = template.render(**render_context)

        job_id = f"{request.lan}_{int(time.time())}"
        audio_file = self.audio_dir / f"{job_id}.mp3"
        vtt_file = self.audio_dir / f"{job_id}.vtt"
        
        # Use a temporary file for text to avoid CLI issues with Unicode/multi-line
        temp_text_file = self.remotion_path / "public" / f"temp_{job_id}.txt"
        temp_text_file.write_text(text_content, encoding='utf-8')

        command = [
            "edge-tts",
            "--file", str(temp_text_file),
            "--voice", voice,
            "--write-media", str(audio_file),
            "--write-subtitles", str(vtt_file)
        ]

        try:
            process = await asyncio.create_subprocess_exec(*command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = await process.communicate()

            if process.returncode != 0:
                print(f"Edge TTS stderr: {stderr.decode()}")
                raise RuntimeError(f"Edge TTS failed: {stderr.decode()}")

            # Extract duration
            audio_info = MP3(str(audio_file))
            duration = audio_info.info.length

            # Parse subtitles
            subtitles = self._parse_vtt(vtt_file)

            # Update metadata.json for Remotion
            self._update_metadata(job_id, duration, subtitles)
            
            return {
                "job_id": job_id,
                "audio_url": f"/remotion_assets/audio/{job_id}.mp3",
                "text": text_content
            }
        finally:
            # Clean up temp text file
            if temp_text_file.exists():
                os.remove(temp_text_file)

    async def render_video(self, job_id: str, language: str = "Hindi") -> Path:
        """
        Triggers Remotion render for a specific job.
        """
        # We need to create a leads.json in the Remotion folder for its current logic
        leads_path = self.remotion_path / "leads.json"
        
        # We need to read existing leads or just create one for this job
        lead_data = [{
            "id": job_id,
            "customer_name": "Valued Customer",
            "lan": job_id,
            "language": language
        }]
        leads_path.write_text(json.dumps(lead_data, ensure_ascii=False), encoding="utf-8")

        output_path = self.output_dir / f"{job_id}.mp4"
        
        # Use npx remotion render
        # comp_id must match the composition ID in Root.tsx
        # In Root.tsx, comp_id = lead.id.replace("_", "-")
        comp_id = job_id.replace("_", "-")
        
        command = [
            "npx.cmd",
            "remotion",
            "render",
            comp_id,
            str(output_path),
            "--overwrite"
        ]

        process = await asyncio.create_subprocess_exec(
            *command, 
            cwd=str(self.remotion_path), 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE
        )
        stdout, stderr = await process.communicate()

        if process.returncode != 0:
            err_msg = stderr.decode()
            print(f"Remotion render error: {err_msg}")
            # Try composition 'main' as fallback if job-specific comp doesn't work
            command = ["npx.cmd", "remotion", "render", "main", str(output_path), "--props", json.dumps({"leadId": job_id}), "--overwrite"]
            process = await asyncio.create_subprocess_exec(*command, cwd=str(self.remotion_path), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = await process.communicate()
            if process.returncode != 0:
                raise RuntimeError(f"Remotion render failed: {stderr.decode()}")

        return output_path
